const sidebars = {
  guideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guide',
    },
  ],
  embeddedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'embedded',
    },
  ],
  robotSidebar: [
    {
      type: 'autogenerated',
      dirName: 'robot/ros2',
    },
  ],
};

export default sidebars;
